---
title: Dart SLL in Lamp. delicata
---

```{r}
library(tidyverse)
library(foreach)
library(parallel)
library(doParallel)
```

```{r}
ldeli.gen = lapply(1:3, function(i) {
    file = paste0("data/Report_DLamp18-3812_SNP_singlerow_", i, ".csv")
    read.csv(file, skip=6, stringsAsFactors=F, na="-")
}) %>%
    bind_rows()

```


```{r}
rownames(ldeli.gen) = paste0("snp", 1:nrow(ldeli.gen))
gen.meta = ldeli.gen[, 1:17]
gen.mat = as.matrix(ldeli.gen[, -1:-17])
gen.mat[gen.mat=="-"] = NA
class(gen.mat) = "numeric"
gen.mat[gen.mat==2] = 88
gen.mat[gen.mat==1] = 2
gen.mat[gen.mat==88] =  1
rownames(gen.mat) = rownames(ldeli.gen[, -1:-17])
colnames(gen.mat) = colnames(ldeli.gen[, -1:-17])
```
    
```{r}
hist(gen.meta$CallRate)
hist(gen.meta$RepAvg)
samp.call.rate = 1 - colMeans(is.na(gen.mat))
hist(samp.call.rate)
rep.thresh = 0.99
loci.call.thresh = 0.6
samp.call.thresh = 0.6
gen.mat.filt = gen.mat[
    gen.meta$RepAvg >= rep.thresh & gen.meta$CallRate >= loci.call.thresh,
    samp.call.rate >= samp.call.thresh
]
```

```{r}
dim(gen.mat)
dim(gen.mat.filt)
table(gen.mat.filt)
```

```{r}
ID = colnames(gen.mat.filt)
sex = ifelse(grepl("DAD", ID), "M", ifelse(grepl("MOM", ID), "F", NA))
table(sex)
```

```{r}
nsnp = nrow(gen.mat.filt)
#nsnp = 100000
res = foreach(i=seq_len(nsnp), .combine=bind_rows, .multicombine=T, .maxcombine=10000) %dopar% {
    snp = gen.mat.filt[i, ]

    res = list()
    res[["snp"]] = rownames(gen.mat.filt)[i]
    for (G in 0:2)
        for (S in c("M", "F"))
            res[[paste0(S, G)]] = mean(snp[sex==S] == G, na.rm=T)
    res[["MN"]]=sum(!is.na(snp[sex=="M"]))
    res[["FN"]]=sum(!is.na(snp[sex=="F"]))
    res
}
```

```{r}
mthresh = 0.8
fthresh = 0.95
res.annot = res %>%
    mutate(potential.sex = ifelse(M1 >= mthresh & (F0 >= fthresh | F2 >= fthresh), "xy",
                                  ifelse((M0 >= mthresh | M2 >= mthresh) & F1 >= fthresh, "zw", NA)))

table(res.annot$potential.sex)
sex.loci.stats = res.annot %>%
    filter(!is.na(potential.sex)) %>%
    arrange(M1)

sex.loci.stats %>%
    knitr::kable()

```

```{r}
res %>%
    mutate(Mhom = ifelse(M0 > M2, M0, M2), Fhet=F1, SexBias = Mhom+Fhet) %>%
    arrange(SexBias) %>%
    tail()
```


```{r}
table(gen.mat.filt)
sex.snps = gen.mat.filt[rownames(gen.mat.filt)%in%res.annot$snp, ]
dim(sex.snps)
```

Monte carlo time!!


The below code tried to empirically calculate a null distribution of sex bias
scores, but something's fucky here and it eats heaps of ram before dying. Take
a look again with clear eyes if this is needed.

```{r execute=F}
.par.clust = makeCluster(16, type="FORK", outfile="parlogs.txt")
registerDoParallel(.par.clust)   
nsnp=nrow(gen.mat.filt)
sbthresh = foreach(rep=seq_len(100), .combine=bind_rows,
                   .packages=c("foreach", "dplyr")) %dopar% {
    if (rep == 1) {
        sex2 = sex
    } else  {
        sex2 = sample(sex)
    }
    cat(paste("rep", rep, "\n"))
    nsnp = nrow(gen.mat.filt)
    this = foreach(i=seq_len(nsnp), .combine=bind_rows) %do% {
        res = list("mc.rep"=rep)
        snp = gen.mat.filt[i, ]
        M0 = mean(snp[sex2 == "M"] == 0, na.rm=T)
        M2 = mean(snp[sex2 == "M"] == 2, na.rm=T)
        F1 = mean(snp[sex2 == "F"] == 1, na.rm=T)

        Mhom = M0
        if (M0 < M2) 
            Mhom = M2
        if (Mhom >= mthresh & F1 >= fthresh) {
            res[["potential.sex"]] = "zw"
        } else {
            res[["potential.sex"]] = NA
        }

        res[["Mhom"]] = Mhom
        res[["Fhet"]] = F1
        res[["SexBias"]] = Mhom + F1
        res
    }
    this %>%
        arrange(-SexBias) %>%
        head(1000)
}
stopCluster(.par.clust)
```
