---
title: 'Methods text for ldeli growth'
author: Fonti Kar
date: "`r Sys.Date()`"
output: 
  word_document:
    reference_docx: "Style_guide.docx"
  html_document:
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

To test whether incubation treatment influence the overall heritaibility of mass and the relative contributions of mass variance (regardless of age), we fitted intercept models for each incubation treatment with random intercepts for both lizard identity and dam identity. We included another random intercept for lizard identity to partition out permanent environvmental effects. Heritability of mass ((regardless of age)) was calculated as: 
$$h^2 = \displaystyle \frac{G_{I}}{(G_{I} + M_{I} + PE_{I} + R_{I})}$$
where $G_{I}$ is the additive genetic variance for all lizards, $M_{I}$ is the variance attributed to dams, $PE_{I}$ is the permenent environmental variance and  $R_{I}$ is the residual variance.

We were also interested in quantifying the changes in heritability and the relative contributions of growth variance with age for each incubation treatment. To address this, we fitted an intercept only model for each treatment group with a random intercept, linear slope and a quadratic term for lizard identity and dam identity. Again, lizard identity was also included as a random intercept to estimate permenant environment effects. We estimated genetic variance-covariance matrix for each treatment ($G$), where the diagonal elements are the additive genetic variances for the intercept ($G_{I}$), slope ($G_{S}$) and the curvature ($G_{C}$) of the growth curve. The off-diagonal elements are the additive genetic covariances between the growth curve parameters, for example,  $Cov_{I,C}$ is the additive genetic variance between the intercept and the curvature. 

$$G = \begin{bmatrix}
G_{I} & Cov_{I,S} & Cov_{I,C}\\ 
Cov_{I,S} & G_{S} & Cov_{S,C}\\
Cov_{I,C}  & Cov_{S,C} & G_{C}
\end{bmatrix}$$

Similarly, the variance-covariance matrix for dams ($M$) can be decomposed in the same manner as $G$.
$$M = \begin{bmatrix}
M_{I} & Cov_{I,S} & Cov_{I,C}\\ 
Cov_{I,S} & M_{S} & Cov_{S,C}\\
Cov_{I,C}  & Cov_{S,C} & M_{C}
\end{bmatrix}$$

We expected that the relative contributions of variance to change with age and treatment differences may manfiest at specific ages. For each treatment group, we calculated additive genetic variance at a given age $G_{x}$ using the random linear and quadratic slope terms as follows,
$$G_{x} = G_{I} + (x^2.G_{S}) + (x^4.G_{C}) + (2x.Cov_{I,S}) + (2x^2.Cov_{I,C}) + (2x^3.Cov_{S,C})$$
where $x$ is a specific age that is substituted throughout the equation in order to estimate age specific values. Age specific dam variance can also be calculated by replacing the relevant variance components using $M$. Age specific heritability is thus a ratio of all variance components at a given age,
$$h^2_{x} = \displaystyle \frac{G_{x}}{(G_{x} + M_{x} + PE_{I} + R_{I})} $$
We calculated age specific additive genetic variance, dam variance and hertaibility for the overall population as well as each treatment group from ages 0 -- 500 days. 